### PR TITLE
MainBody Component

### PR DESCRIPTION
**Pull request by iCarloscz**
Now mainbody shows a loading bar when is loading the data.

### CODE REVIEW

**Comment by iCarloscz** [comment]
Now is ready to merge i guess. @jac1013

**Comment by jac1013** [comment]
@iCarloscz something's not right here, why in All Articles there are no articles appearing? And in About me I can see that the server is being called, the about me is being returned but the client is not showing it?

I think we need to fix this before merging

**Comment by jac1013** [comment]
@iCarloscz any fix for this yet?

**Review by jac1013 — CHANGES_REQUESTED** [review]
Please what I mentioned in the comment.

**Review by jac1013 — APPROVED** [review]

**Pull request merged**
